### ISSUE TITLE
Header Menu: Sub-menu is not styled and active state is not working properly on devices. 

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#14]
![ipad_and_ipadmini](https://cloud.githubusercontent.com/assets/13309730/10603963/dfcef0be-773e-11e5-87be-d8f573add18e.png)

**Comment by nakul-titan** [comment]
Sub-menus are designed as per psd it is correct. Please mark label as question if anything is not clear.

**Comment by mahender-sowedane** [comment]
Sub-menu text disappeared when moving cursor from second level menu to third level menu.

![2015-11-06_1720-menu01](https://cloud.githubusercontent.com/assets/13309730/10996493/4929bb2e-84ab-11e5-9281-0488bc441daf.png)

**Comment by nakul-titan** [comment]
Second level of menu styling is sufficient.

**Comment by roseliesromeo** [comment]
Refer to bug #105
