### ISSUE TITLE
Home page- Header: Social link section left and right side gap should be equal on mobile devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#15]
![screenshot_2015-10-20-09-38-09](https://cloud.githubusercontent.com/assets/13309730/10604009/3bdd5198-773f-11e5-969d-a453c86e25bb.png)

**Comment by nakul-titan** [comment]
The are align to menu.

**Comment by nakul-titan** [comment]
As mention above it is aligned with menu.
