### ISSUE TITLE
Lead-in's: There is no proper alignment for lead-ins on mobile devices.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#19]
![screenshot_2015-10-20-12-43-59](https://cloud.githubusercontent.com/assets/13309730/10604548/afaeaae2-7742-11e5-8111-582e33ad86c0.png)

**Comment by mahender-sowedane** [comment]
Still bug is not fixed, Broken alignment if newly added lead-in's.

![untitled-lead-ins](https://cloud.githubusercontent.com/assets/13309730/10966489/eac99b16-83d9-11e5-8546-8d596d19cb99.png)

**Comment by nakul-titan** [comment]
All lead-ins are center aligned.
