### ISSUE TITLE
Manufacturing - mckay-queensland: Manufacturing listing-page is not implemented as per psd.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#35]
![psd](https://cloud.githubusercontent.com/assets/13309730/10607046/66c218fc-7754-11e5-8497-f6a8d2fef212.png)

**Comment by nakul-titan** [comment]
We have to implement design as per "14b-TRI-manufacturing.psd" not as "14-TRI-manufacturing.psd",
Please mark label as 'question' if anything is not cleat to you.

**Comment by mahender-sowedane** [comment]
Could you please give me explanation why it's invalid?
As per psd manufacturing listing page must be implemented and Find Out More link will be necessary for the listing page.
thanks!

**Comment by nakul-titan** [comment]
There are two designs for each page and as per Jolene's email we have to follow design "b".
