### ISSUE TITLE
Header section: Social link's section icon's are not aligned properly and As per psd there is no gap between message & phone number icon's.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#37]
![2015-11-16_1053-header01](https://cloud.githubusercontent.com/assets/13309730/11174887/fac35230-8c50-11e5-8df3-454729e7b27f.png)

**Comment by mahender-sowedane** [comment]
Still banner is distorting while loading the site on IE 9,10 & 11 and also getting FOUC Problem.

![untitled-ie](https://cloud.githubusercontent.com/assets/13309730/10965643/862a9372-83d4-11e5-9c4e-08558538ddae.png)

**Comment by nakul-titan** [comment]
IE9 doesn't support animation and due to that caption is taking a second to load.

**Comment by mahender-sowedane** [comment]
Have look that above screenshot, it is IE11(i.e IE-edge)
still bug is not fixed

**Comment by mahender-sowedane** [comment]
Still not fixed.

![2015-11-17_1420-header](https://cloud.githubusercontent.com/assets/13309730/11206674/9bdc661c-8d36-11e5-8043-bf2e33d800f7.png)
