### ISSUE TITLE
Gallery page: There is always a missing image in the galleries

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#38]
![2015-11-18_1439-res990](https://cloud.githubusercontent.com/assets/13309730/11238367/1d1e93a6-8e0b-11e5-845b-93d062796a26.png)

**Comment by mahender-sowedane** [comment]
Pagination is too close with thumbnails in gallery page 'page2' and also alignment is broken

![2015-11-05_1219-gallery_page2](https://cloud.githubusercontent.com/assets/13309730/10967070/f9835be8-83dd-11e5-9b01-977ea7218264.png)

**Comment by mahender-sowedane** [comment]
Still bug is not fixed on services single pages and also pagination is broken, have a look this screen

![services-02](https://cloud.githubusercontent.com/assets/13309730/11061249/d0049498-87cb-11e5-9678-3fa3d60614fe.png)

**Comment by mahender-sowedane** [comment]
Still not fixed for Gallery page on devices.

Devices:
Ipad (Portrait)
Itouch (Portrait & Landscape)
E7 (Portrait & Landscape)

![img_0837](https://cloud.githubusercontent.com/assets/13309730/11206822/8bb1dc26-8d37-11e5-86e6-26580f694f9f.PNG)

**Comment by mahender-sowedane** [comment]
Still not fixed, have a look this screen.

![2015-11-20_162-gallery](https://cloud.githubusercontent.com/assets/13309730/11298292/e1047ada-8fa3-11e5-88e8-a325fcbd28e3.png)

**Comment by mahender-sowedane** [comment]
Still not fixed.

![gallery1 - tricon drilling solutions 2015-11-23 16-12-13](https://cloud.githubusercontent.com/assets/13309730/11334811/90bd541e-91fd-11e5-845c-0bb54c944149.png)

**Comment by nakul-titan** [comment]
If you are creating new gallery pages then please use "Gallery" template in backend don't use default template. 
![edit page tricon drilling solutions wordpress 2015-11-23 18-17-16](https://cloud.githubusercontent.com/assets/13461911/11336843/8752c1fa-920e-11e5-8a19-686ad0d67d44.png)

**Comment by mahender-sowedane** [comment]
I'm aware of that, i just tried to add album's on admin that's it.
Still Extended album is not styled.

![untitled-gallery](https://cloud.githubusercontent.com/assets/13309730/11361069/56cbfd1a-92b0-11e5-8dce-36f9baf4da15.png)
