### ISSUE TITLE
Sitemap page: Ordered/unordered list items are not styled.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#42]
Applicable to all pages.

![sitemap01](https://cloud.githubusercontent.com/assets/13309730/10607567/02b311f0-7758-11e5-98cf-08871186e117.png)

**Comment by mahender-sowedane** [comment]
Still bug is not fixed and applicable for all single pages.

![untitled-2](https://cloud.githubusercontent.com/assets/13309730/10937556/8dd516c6-8319-11e5-9544-8e4745074cfb.png)

**Comment by mahender-sowedane** [comment]
Still not fixed

![sitemap - 001](https://cloud.githubusercontent.com/assets/13309730/11061329/55fd80e6-87cc-11e5-9650-63a7e7a32e75.png)

**Comment by nakul-titan** [comment]
It is as per design.

**Comment by mahender-sowedane** [comment]
Still not fixed. Applicable to all pages.

![about us - tricon03](https://cloud.githubusercontent.com/assets/13309730/11143381/a8257810-8a1a-11e5-94d0-a005ddb0da82.png)

**Comment by mahender-sowedane** [comment]
Still not fixed

![about us -lists01](https://cloud.githubusercontent.com/assets/13309730/11175104/813e19b4-8c54-11e5-9b92-210d2d6f53d5.png)

**Comment by nakul-titan** [comment]
Please try to put lists in a proper order don't mix ul/ol lists.
