### ISSUE TITLE
Lead-in's(Home page): Lead-ins not connected to correct pages. Lead-in links not editable in the CMS.

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#57]

**Comment by nakul-titan** [comment]
I think by mistake somebody have deleted Lead-ins ACF field at the backend due to which it is redirection to wrong page, I have recreated Lead-ins ACF page link field.

**Comment by mahender-sowedane** [comment]
I don't think so, I didn't find Lead-ins ACF field while testing in admin panel may be your not created.
if your created then who will delete that link field, every changes should be recorded & updated at our central repository. So mistake should be accept & don't blame others.
Now bug is fixed.
Thanks!
