### ISSUE TITLE
Products single pages: On products single pages, mouse-over on buttons to have rounded corners

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#74]
![single-bug17rounded](https://cloud.githubusercontent.com/assets/13309730/11110487/86030b88-8922-11e5-8e32-87234c27357e.png)

**Comment by nakul-titan** [comment]
It is rectangle in PSD. 
![07b-tri-product-single](https://cloud.githubusercontent.com/assets/13461911/11111079/e90a7470-892a-11e5-944f-270ef42a1afa.jpg)

**Comment by mahender-sowedane** [comment]
And also Default-no image is not implemented for products single pages, there is no proper alignment below the image gallery as per psd.

![de-watering tool dwt - image01](https://cloud.githubusercontent.com/assets/13309730/11113505/8ac47046-8943-11e5-9359-682ae3686ecd.png)
