### ISSUE TITLE
General: FOUC exists. All banner images are displayed on page load

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#76]
![2015-11-13_1504-tricon_banner001](https://cloud.githubusercontent.com/assets/13309730/11143045/1eca49f8-8a18-11e5-8c86-e7f1c0e68a82.png)

**Comment by mahender-sowedane** [comment]
It's not duplicate, if it's duplicate give me link or clear clarification.

**Comment by nakul-titan** [comment]
Bug #37 is same issue.
https://github.com/titan-cebu/Tricon-Drilling-Solutions/issues/37

**Comment by mahender-sowedane** [comment]
Issue #37 has been updated, please fix this issue now.
thanks!

**Comment by mahender-sowedane** [comment]
![2015-11-17_0830-fouc](https://cloud.githubusercontent.com/assets/13309730/11201623/9f4e4f62-8d05-11e5-8c9d-9dc1c5b18880.png)

**Comment by mahender-sowedane** [comment]
Not fixed.

![2015-11-23_0852-fouc](https://cloud.githubusercontent.com/assets/13309730/11329776/18f07a5a-91c7-11e5-9b35-67bc0f9b7292.png)

**Comment by mahender-sowedane** [comment]
Still not fixed.
'Tried disabling JS on this site and there will be a loading display shouldn't displayed empty space'

![2015-11-24_0937-fouc](https://cloud.githubusercontent.com/assets/13309730/11357707/6b0ab796-9290-11e5-9244-a316203f2eef.png)
