### ISSUE TITLE
Footer - Section: Missing active state behaviour only the hover state behaviour applied

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#84]
![2015-11-17_1134-footer01](https://cloud.githubusercontent.com/assets/13309730/11203980/c020c6e2-8d1f-11e5-97c3-743bf09cfc44.png)

**Comment by nakul-titan** [comment]
As per design there is no active or hover state for footer.

**Comment by mahender-sowedane** [comment]
Observe the footer section in psd file or have a look this screen below and fix it properly.
thanks!

![2015-11-20_1614-footer_active](https://cloud.githubusercontent.com/assets/13309730/11298029/42da7a04-8fa2-11e5-935d-1d61615608b0.png)
