### ISSUE TITLE
Lead-in's section: Shouldn't use transperant image's instead of background-color css3 style(rgba).

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Tricon-Drilling-Solutions#93]
Applicable to all lead-in's in home page.

![2015-11-23_1354](https://cloud.githubusercontent.com/assets/13309730/11333217/1dfdea02-91f2-11e5-9f64-5ffd29127260.png)

**Comment by nakul-titan** [comment]
Background image is used because there are compatibility issues with IE9 and rgb.

**Comment by mahender-sowedane** [comment]
Still not fixed.
If your not understood then discuss with your seniors and fix it properly
thanks!

**Comment by nakul-titan** [comment]
After discussing with Team leader I have wrote above comment.

**Comment by mahender-sowedane** [comment]
After having discussion with my TL then i have re-opened that issue
thanks!
